_sass/navigation.scss, javascript/navigation.coffee
* Haven't been able to disable the tap highlight on the hamburger button.
=> Fixed navigation menu so that it works in mobile Chrome.

bwit/index.html
Chelsea and I think it makes more sense for the dates to be in chronological order.
=> Put dates in chronological order

bwit/faq.html, bwit/index.html
date changed from Tuesday April 4 to Monday April 17
=> Update second BWiT information session date

privacy.html
=> Adds /privacy.html

phoenix-and-elixir.html
@danivovich @yflicker updated the 'description' meta text
=> fixed meta text

_includes/social-media.html, what-makes-us-different.html
Two minor edits: Struck G+ icon from social media in footer; updated years in business on 'what makes us different' to be 13+
@danivovich @yflicker
=> Minor updates

phoenix-and-elixir.html
added copy and link to twitch
@danivovich @yflicker
=> add twitch stream to phoenix / elixir page

index.html, phoenix-and-elixir.html
@yflicker @danivovich 
added mailchimp subscribe forms to home and phoenix / elixir pages - lmk if you think they look ok, I just dropped the code they provide in wholesale, tried to find spots that looked reasonable on the pages.
=> Mailchimp form add

experience.html, phoenix-and-elixir.html
@danivovich @yflicker this is all copy / content edits, updating to include more recent content or make it easier to get to the tech pages.
=> Add feature links

bwit/index.html, case-studies.html, case-study/brookes-publishing.html, case-study/newsup.html, phoenix-and-elixir.html, react-native.html
@danivovich @yflicker Added alt tags where missing from images; no other changes. Should be good to merge.
=> Alt tags for images

case-studies.html
@yflicker copy edit per our slack convo
=> removed ¶ from case studies blurbs

_data/case_studies.yml, _data/clients.yml, _data/elixir_case_studies.yml, _data/featured_case_studies.yml, _data/react_native_case_studies.yml, _data/team.yml, _includes/mailchimp.html, case-studies.html, phoenix-and-elixir.html, react-native.html, team.html
Simplify management of a few pages and make it easier to adjust content.
=> Move items into data files

podcast.html
added s2 copy to the podcast page
=> add copy re: s2

_includes/mailchimp-tracking-script.html, _layouts/default.html
adding tracking script for mailchimp-managed remarketing ads
=> adding tracking script for mailchimp ads

_includes/header-lp.html, _includes/header.html, case-studies/brookes-publishing.html, case-studies/index.html, case-studies/urban-teacher-center.html, contact.html, method.html, services/index.html, technologies/index.html
update to feature blocks, some branding updates for clients
=> Site updates

.github/workflows/podcast.yml
=> Set up a podcast workflow

services/index.html
merging various SEO copy drafting branches
=> Services seo

_includes/rss.html, _layouts/default.html, podcast/elixir-wizards/index.html
@oestrich - I copied the pattern you used for the structured data - still would appreciate a second set of eyes to make sure i didn't do anything weird / wrong with it
=> added header link to rss feed in header on podcast page

software-development/index.html, software-development/mobile-applications.html
mobile application development page
=> Seo updates

_data/elixir_wizards_transcripts.yml, _layouts/podcast-episode.html
Looks like this:
Probably needs more styling?
=> Allow for multiple languages for podcast transcripts

_data/elixir_wizards_transcripts.yml, podcast/elixir-wizards/transcripts/s6e11_MiniFeatures.txt
Add transcript for S6E11 - Mini Feature extravaganza
=> Transcript add s6e11 minifeatures

_data/elixir_wizards_transcripts.yml, podcast/elixir-wizards/transcripts/s6e12_Amos_King.txt
Add transcript for S6E12 - Amos King
=> Transcript addepisode s6e12 amos king

podcast/elixir-wizards/transcripts/s7e6-klosko.txt
=> The name of his university is AGH

_includes/overview_hero.html, _sass/components/overview_hero.scss
Update the copy in the overview hero and add button "Reserve Session", ensuring everything is responsive on mobile.
=> Update Copy and Add Button to Overview Hero
